# packages in environment at C:\Users\hansh\anaconda3\envs\DBnr3:
#
# Name                    Version                   Build  Channel
asgiref                   3.5.0                    pypi_0    pypi
beautifulsoup4            4.9.3                    pypi_0    pypi
boto3                     1.17.93                  pypi_0    pypi
botocore                  1.20.93                  pypi_0    pypi
ca-certificates           2022.2.1             haa95532_0  
certifi                   2021.10.8        py39haa95532_2  
crispy-bootstrap5         0.4                      pypi_0    pypi
dj-database-url           0.5.0                    pypi_0    pypi
django                    3.1.6                    pypi_0    pypi
django-bootstrap-v5       1.0.4                    pypi_0    pypi
django-crispy-forms       1.12.0                   pypi_0    pypi
django-filter             2.4.0                    pypi_0    pypi
django-heroku             0.3.1                    pypi_0    pypi
django-storages           1.11.1                   pypi_0    pypi
gunicorn                  20.1.0                   pypi_0    pypi
importlib-metadata        3.10.1                   pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
openssl                   1.1.1m               h2bbff1b_0  
pillow                    8.1.0                    pypi_0    pypi
pip                       21.2.4           py39haa95532_0  
psycopg2                  2.8.6                    pypi_0    pypi
psycopg2-binary           2.8.6                    pypi_0    pypi
python                    3.9.7                h6244533_1  
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
s3transfer                0.4.2                    pypi_0    pypi
setuptools                58.0.4           py39haa95532_0  
six                       1.16.0                   pypi_0    pypi
soupsieve                 2.2                      pypi_0    pypi
sqlite                    3.37.2               h2bbff1b_0  
sqlparse                  0.4.1                    pypi_0    pypi
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wheel                     0.37.1             pyhd3eb1b0_0  
whitenoise                5.2.0                    pypi_0    pypi
wincertstore              0.2              py39haa95532_2  
zipp                      3.5.0                    pypi_0    pypi
